---
title: "longitudinal_cfa_isolation"
author: "Katherine N Thompson"
date: "7th June 2021"
output:
  word_document:
    toc: yes
    toc_depth: '2'
  html_document:
    df_print: paged
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: no
    number_sections: no
    highlight: monochrome
    theme: cerulean
code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      comment = NA,
                      prompt = FALSE,
                      cache = FALSE,
                      message = FALSE,
                      warning = FALSE)

options(bitmapType = 'quartz') # to render fonts better
```

```{r Clear global environment}
remove(list = ls())
```

```{r Load packages}
library(summarytools)
library(lavaan)
library(knitr)
library(tidyverse)
library(dplyr) #conflicts with tidyverse for e.g. rename and row_number
```

```{r source the data file path}
#source raw data directory: data_raw and data included
source("../../../../../isolation_trajectories_data_path.R")
```

```{r read in prepped regression data and check variable names, include=FALSE}
dat <- readRDS(file = paste0(data_path, "preprocessed_isolation_trajectories_Jan2021_full_sample.rds"))
colnames(dat)
```

everything to the left of =~ is the factor and to the right are the items to load on that factor

```{r set configural invariance model}
config.isolation <-'
                    #factor loadings
                    sc08 =~ NA*flgd08 + L.f*flgd08 + worth08 + satis08 + nogd08
                    sc10 =~ NA*flgd10 + L.f*flgd10 + worth10 + satis10 + nogd10
                    sc12 =~ NA*flgd12 + L.f*flgd12 + worth12 + satis12 + nogd12
          
                    #means/intercepts
                    sc08 ~ 0*1
                    sc10 ~ start(0)*1
                    sc12 ~ start(0)*1
                    flgd08 ~ I.f*1
                    flgd10 ~ I.f*1
                    flgd12 ~ I.f*1
          
                    #variances/covariances
                    sc08 ~~ 1*sc08
                    sc10 ~~ start(1)*sc10
                    sc12 ~~ start(1)*sc12
                    flgd08 ~~ flgd10 + flgd12 
                    flgd10 ~~ flgd12 
                    worth08 ~~ worth10 + worth12 
                    worth10 ~~ worth12 
                    satis08 ~~ satis10 + satis12 
                    satis10 ~~ satis12 
                    nogd08 ~~ nogd10 + nogd12 
                    nogd10 ~~ nogd12 
                   '
```

```{r fit configural invariance model}
fit.config.isolation <- sem(config.isolation, 
                            sample.cov = sc.cov, 
                            sample.mean = sc.mns, 
                            sample.nobs = 228, 
                            meanstructure = TRUE)

summary(fit.config.isolation, 
        fit.measures = TRUE, 
        estimates = TRUE)
```

```{r set weak invariance model}
weak.isolation <-'
                  #factor loadings
                  sc08 =~ NA*flgd08 + L.f*flgd08 + L.w*worth08 + 
                          L.s*satis08 + L.n*nogd08
                  sc10 =~ NA*flgd10 + L.f*flgd10 + L.w*worth10 + 
                          L.s*satis10 + L.n*nogd10
                  sc12 =~ NA*flgd12 + L.f*flgd12 + L.w*worth12 + 
                          L.s*satis12 + L.n*nogd12
          
                  #means/intercepts
                  sc08 ~ 0*1
                  sc10 ~ start(0)*1
                  sc12 ~ start(0)*1
                  flgd08 ~ I.f*1
                  flgd10 ~ I.f*1
                  flgd12 ~ I.f*1
          
                  #variances/covariances
                  sc08 ~~ 1*sc08
                  sc10 ~~ start(1)*sc10
                  sc12 ~~ start(1)*sc12
                  flgd08 ~~ flgd10 + flgd12 
                  flgd10 ~~ flgd12 
                  worth08 ~~ worth10 + worth12 
                  worth10 ~~ worth12 
                  satis08 ~~ satis10 + satis12 
                  satis10 ~~ satis12 
                  nogd08 ~~ nogd10 + nogd12 
                  nogd10 ~~ nogd12 
                 '
```

```{r fit weak invariance model}
fit.weak.isolation <- sem(weak, 
                          sample.cov = sc.cov, 
                          sample.mean = sc.mns, 
                          sample.nobs = 228, 
                          meanstructure = TRUE)

summary(fit.weak, 
        fit.measures = TRUE, 
        estimates = TRUE)
```

```{r test config and weak}
# test for a difference between the config model and the weak model (want it to be non-sig)
lavTestLRT(fit.weak, fit.config)
```

```{r set strong invariance model}
strong.isolation <-'
                    #factor loadings
                    sc08 =~ NA*flgd08 + L.f*flgd08 + L.w*worth08 + 
                            L.s*satis08 + L.n*nogd08
                    sc10 =~ NA*flgd10 + L.f*flgd10 + L.w*worth10 + 
                            L.s*satis10 + L.n*nogd10
                    sc12 =~ NA*flgd12 + L.f*flgd12 + L.w*worth12 + 
                            L.s*satis12 + L.n*nogd12
          
                    #means/intercepts
                    sc08 ~ 0*1
                    sc10 ~ start(0)*1
                    sc12 ~ start(0)*1
                    flgd08 ~ I.f*1
                    flgd10 ~ I.f*1
                    flgd12 ~ I.f*1
                    worth08 ~ I.w*1
                    worth10 ~ I.w*1
                    worth12 ~ I.w*1
                    satis08 ~ I.s*1
                    satis10 ~ I.s*1
                    satis12 ~ I.s*1
                    nogd08 ~ I.n*1
                    nogd10 ~ I.n*1
                    nogd12 ~ I.n*1
          
                    #variances/covariances
                    sc08 ~~ 1*sc08
                    sc10 ~~ start(1)*sc10
                    sc12 ~~ start(1)*sc12
                    flgd08 ~~ flgd10 + flgd12 
                    flgd10 ~~ flgd12 
                    worth08 ~~ worth10 + worth12 
                    worth10 ~~ worth12 
                    satis08 ~~ satis10 + satis12 
                    satis10 ~~ satis12 
                    nogd08 ~~ nogd10 + nogd12 
                    nogd10 ~~ nogd12 
                   '
```

```{r strong invariance model}
fit.strong <- sem(strong, 
                  sample.cov = sc.cov, 
                  sample.mean = sc.mns, 
                  sample.nobs = 228, 
                  meanstructure = TRUE)

summary(fit.strong, 
        fit.measures = TRUE, 
        estimates = TRUE)
```

```{r}
lavTestLRT(fit.strong, fit.weak)
```


```{r}
#request modification indices
mi<-lavTestScore(fit.strong)
mi$uni[order(-mi$uni$X2),]
parTable(fit.strong)

#M.I.s tell us to relax equality of intercepts on Nogd12, and
#there is no indication the constraints on satis08 also need
#to be relaxed. This is different from the results we
#would obtain in Mplus. To maintain consistency with the course
#lecture, we assume the M.I.s from Mplus. The larger modification 
#index in Mplus suggested that satis08 should have a higher 
#intercept than satis10 and satis12 (modification index = 8.5), 
```


















